#version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    networks:
      - mi_red
    depends_on:
      - mariadb
    restart: always 

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend  
    networks:
      - mi_red

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - mi_red

networks:
  mi_red:
